import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { GTAOPass } from 'three/addons/postprocessing/GTAOPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { FullScreenQuad } from 'three/addons/postprocessing/Pass.js';

/** Only solid surfaces contribute to contact occlusion. Leaf cards and water
 * must retain their real alpha silhouettes instead of casting rectangular AO. */
class GardenOcclusion extends GTAOPass {
  private hidden: THREE.Object3D[] = [];
  private cached = false;
  private capturedWorld = new THREE.Matrix4();
  private capturedProjection = new THREE.Matrix4();
  private cachedQuad = new FullScreenQuad(this.copyMaterial);

  invalidate() { this.cached = false; }

  private cameraUnchanged() {
    const close = (a: THREE.Matrix4, b: THREE.Matrix4) => a.elements.every((value, i) => Math.abs(value - b.elements[i]) < 0.00001);
    return close(this.camera.matrixWorld, this.capturedWorld) && close(this.camera.projectionMatrix, this.capturedProjection);
  }

  override dispose() {
    // These two materials are omitted by GTAOPass.dispose in Three r180.
    this.gtaoMaterial.dispose();
    this.blendMaterial.dispose();
    this.cachedQuad.dispose();
    super.dispose();
  }

  override render(renderer: THREE.WebGLRenderer, write: THREE.WebGLRenderTarget, read: THREE.WebGLRenderTarget) {
    // Once the camera settles, the veranda, stones and shrub cores do not
    // change. Reuse their contact shading instead of redrawing the whole garden
    // into a normal buffer on every frame. Moving objects never enter this map.
    if (this.cached && this.cameraUnchanged()) {
      const autoClear = renderer.autoClear;
      renderer.autoClear = false;
      renderer.setRenderTarget(this.renderToScreen ? null : write);
      this.copyMaterial.uniforms.tDiffuse.value = read.texture;
      this.copyMaterial.blending = THREE.NoBlending;
      this.cachedQuad.material = this.copyMaterial;
      this.cachedQuad.render(renderer);
      this.blendMaterial.uniforms.intensity.value = this.blendIntensity;
      this.blendMaterial.uniforms.tDiffuse.value = this.pdRenderTarget.texture;
      this.cachedQuad.material = this.blendMaterial;
      this.cachedQuad.render(renderer);
      renderer.autoClear = autoClear;
      return;
    }
    const autoUpdate = renderer.shadowMap.autoUpdate;
    const needsUpdate = renderer.shadowMap.needsUpdate;
    // Normal/depth rendering hides foliage; it must not overwrite the actual
    // alpha-tested sun shadows generated by the preceding colour pass.
    renderer.shadowMap.autoUpdate = false;
    renderer.shadowMap.needsUpdate = false;
    this.scene.traverse(object => {
      if (!object.visible) return;
      if (object instanceof THREE.Sprite) {
        object.visible = false;
        this.hidden.push(object);
      } else if (object instanceof THREE.Mesh) {
        const materials = Array.isArray(object.material) ? object.material : [object.material];
        let dynamic = false;
        for (let ancestor: THREE.Object3D | null = object; ancestor; ancestor = ancestor.parent) {
          if (ancestor.userData.skipAO || ancestor.name === 'glass-furin' || ancestor.name === 'falling-fish-food') { dynamic = true; break; }
        }
        const fineFoliage = object instanceof THREE.InstancedMesh && materials.some(material => material.side === THREE.DoubleSide);
        if (dynamic || fineFoliage || materials.some(material => material.transparent || material.alphaTest > 0)) {
          object.visible = false;
          this.hidden.push(object);
        }
      }
    });
    try {
      super.render(renderer, write, read, 0, false);
      this.capturedWorld.copy(this.camera.matrixWorld);
      this.capturedProjection.copy(this.camera.projectionMatrix);
      this.cached = true;
    }
    finally {
      renderer.shadowMap.autoUpdate = autoUpdate;
      renderer.shadowMap.needsUpdate = needsUpdate;
      for (const object of this.hidden) object.visible = true;
      this.hidden.length = 0;
    }
  }
}

export function createRendering(renderer: THREE.WebGLRenderer, scene: THREE.Scene, camera: THREE.PerspectiveCamera) {
  renderer.info.autoReset = false;
  const target = new THREE.WebGLRenderTarget(1, 1, { type: THREE.HalfFloatType, samples: 2 });
  const composer = new EffectComposer(renderer, target);
  const colorPass = new RenderPass(scene, camera);
  const occlusion = new GardenOcclusion(scene, camera, 1, 1);
  occlusion.updateGtaoMaterial({ radius: 0.7, distanceExponent: 1.4, thickness: 0.6, distanceFallOff: 1.2, samples: 8 });
  occlusion.updatePdMaterial({ radius: 4, rings: 2, samples: 8 });
  occlusion.blendIntensity = 0.65;
  const output = new OutputPass();
  composer.addPass(colorPass);
  composer.addPass(occlusion);
  composer.addPass(output);
  let width = 1, height = 1;
  let resolution = Math.min(renderer.getPixelRatio(), 1.25);
  let previousFrame = 0, slowFrames = 0;
  const startedAt = performance.now();
  function sizeTargets() {
    composer.setPixelRatio(resolution);
    composer.setSize(width, height);
    // AO describes broad contact, not individual leaf edges. Cap its pixel
    // budget independently from the crisp color render and its two-sample MSAA.
    const factor = Math.min(0.5, (width < 760 ? 480 : 720) / Math.max(width, height));
    occlusion.setSize(Math.max(1, Math.round(width * factor)), Math.max(1, Math.round(height * factor)));
    occlusion.invalidate();
  }
  return {
    invalidate() { occlusion.invalidate(); },
    resize(nextWidth: number, nextHeight: number) {
      width = nextWidth; height = nextHeight;
      sizeTargets();
    },
    render() {
      const now = performance.now();
      const interval = now - previousFrame;
      previousFrame = now;
      // Ignore compilation/startup and background-tab gaps. Sustain a modest
      // pixel budget on slower GPUs rather than disabling reflections or AO.
      if (now - startedAt > 2500 && interval > 45 && interval < 1000) slowFrames++;
      else slowFrames = 0;
      if (slowFrames >= 12 && resolution > 0.85) {
        resolution = Math.max(0.85, resolution * 0.82);
        slowFrames = 0;
        sizeTargets();
      }
      renderer.info.reset();
      composer.render();
    },
    dispose() { colorPass.dispose(); occlusion.dispose(); output.dispose(); composer.dispose(); },
  };
}
